# Generated by Django 5.1.8 on 2026-01-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSpendDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("platform", models.CharField(max_length=50)),
                ("account_id", models.CharField(max_length=255)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_spend_daily",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Spend Daily",
                "verbose_name_plural": "Ad Spend Daily",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="analytics_a_organiz_c911a3_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_a_date_fbb1b4_idx"),
                    models.Index(
                        fields=["platform", "date"],
                        name="analytics_a_platfor_9a49ec_idx",
                    ),
                    models.Index(
                        fields=["account_id", "date"],
                        name="analytics_a_account_de21fb_idx",
                    ),
                    models.Index(
                        fields=["organization", "date"],
                        name="analytics_a_organiz_d4985a_idx",
                    ),
                ],
                "unique_together": {("organization", "date", "platform", "account_id")},
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "store_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("orders_count", models.IntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("new_customers_count", models.IntegerField(default=0)),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("spend_by_platform", models.JSONField(blank=True, default=dict)),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "roas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("mer", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "net_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "ncpa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_sync_at", models.DateTimeField(auto_now=True)),
                ("data_source", models.CharField(default="live", max_length=20)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Metrics",
                "verbose_name_plural": "Daily Metrics",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="analytics_d_organiz_b23529_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_d_date_24cb73_idx"),
                    models.Index(
                        fields=["organization", "date"],
                        name="analytics_d_organiz_ac7a9f_idx",
                    ),
                ],
                "unique_together": {("organization", "date", "store_id")},
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "trend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("trend_label", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=50)),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("up", "Up"),
                            ("down", "Down"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20)),
                ("order", models.IntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="analytics_m_organiz_cbbacd_idx"
                    ),
                    models.Index(fields=["order"], name="analytics_m_order_751e3f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_data",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Data",
                "verbose_name_plural": "Performance Data",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="analytics_p_organiz_661ee3_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_p_date_1ea248_idx"),
                    models.Index(
                        fields=["organization", "date"],
                        name="analytics_p_organiz_bbbabd_idx",
                    ),
                ],
                "unique_together": {("organization", "date")},
            },
        ),
        migrations.CreateModel(
            name="PlatformSpend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(max_length=50)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("color", models.CharField(default="#000000", max_length=20)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_spend",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Spend",
                "verbose_name_plural": "Platform Spend",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="analytics_p_organiz_7f586b_idx"
                    )
                ],
                "unique_together": {("organization", "platform")},
            },
        ),
    ]
