# Generated by Django 5.1.8 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymetrics",
            name="revenue_by_source",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
