# Generated by Django 5.1.8 on 2026-02-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_apikey_accounts_ap_organiz_18cc7e_idx_and_more"),
        ("analytics", "0002_dailymetrics_revenue_by_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymetrics",
            name="expenses_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="gross_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="total_expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="total_refunds",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("cogs", "Cost of Goods Sold"),
                            ("shipping", "Shipping/Fulfillment"),
                            ("handling", "Handling Fees"),
                            ("payment_gateway", "Payment Gateway Fees"),
                            ("taxes", "Operational Taxes"),
                            ("custom", "Custom Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expense_date", models.DateField(db_index=True)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("one_time", "One-time"),
                            ("daily", "Daily"),
                            ("monthly", "Monthly"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("recurrence_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="analytics_e_organiz_43060c_idx"
                    ),
                    models.Index(
                        fields=["expense_date"], name="analytics_e_expense_62c286_idx"
                    ),
                    models.Index(
                        fields=["organization", "expense_date"],
                        name="analytics_e_organiz_4a2a90_idx",
                    ),
                    models.Index(
                        fields=["expense_type"], name="analytics_e_expense_fdfdde_idx"
                    ),
                ],
            },
        ),
    ]
