# Generated by Django 5.1.8 on 2026-01-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=500)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Meta", "Meta"),
                            ("Google", "Google"),
                            ("TikTok", "TikTok"),
                            ("Snapchat", "Snapchat"),
                            ("X", "X"),
                            ("Klaviyo", "Klaviyo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Paused", "Paused"),
                            ("Learning", "Learning"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Inactive",
                        max_length=20,
                    ),
                ),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "roas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "cpa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="campaigns_c_organiz_46a505_idx"
                    ),
                    models.Index(
                        fields=["platform"], name="campaigns_c_platfor_b45c00_idx"
                    ),
                    models.Index(
                        fields=["status"], name="campaigns_c_status_96cb56_idx"
                    ),
                    models.Index(
                        fields=["external_id"], name="campaigns_c_externa_743c99_idx"
                    ),
                    models.Index(
                        fields=["organization", "platform"],
                        name="campaigns_c_organiz_86226e_idx",
                    ),
                ],
                "unique_together": {("organization", "external_id")},
            },
        ),
    ]
