# Generated by Django 5.1.8 on 2026-01-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(db_index=True, max_length=255)),
                ("store_id", models.CharField(db_index=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("salla", "Salla"),
                            ("zid", "Zid"),
                            ("shopify", "Shopify"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateTimeField(db_index=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("status", models.CharField(max_length=50)),
                ("customer_id", models.CharField(blank=True, max_length=255)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("is_new_customer", models.BooleanField(blank=True, null=True)),
                ("attributed_platform", models.CharField(blank=True, max_length=50)),
                ("attributed_click_id", models.CharField(blank=True, max_length=255)),
                (
                    "attribution_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="orders_orde_organiz_97975a_idx"
                    ),
                    models.Index(
                        fields=["external_id"], name="orders_orde_externa_66d462_idx"
                    ),
                    models.Index(
                        fields=["store_id"], name="orders_orde_store_i_6ed055_idx"
                    ),
                    models.Index(
                        fields=["order_date"], name="orders_orde_order_d_d71205_idx"
                    ),
                    models.Index(
                        fields=["source"], name="orders_orde_source_e5e59d_idx"
                    ),
                    models.Index(
                        fields=["organization", "order_date"],
                        name="orders_orde_organiz_da588b_idx",
                    ),
                ],
                "unique_together": {("organization", "external_id", "source")},
            },
        ),
    ]
