# Generated by Django 5.1.8 on 2026-02-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_apikey_accounts_ap_organiz_18cc7e_idx_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(db_index=True, max_length=255)),
                ("refund_date", models.DateTimeField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="orders.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="orders_refu_organiz_ad78aa_idx"
                    ),
                    models.Index(
                        fields=["refund_date"], name="orders_refu_refund__384984_idx"
                    ),
                    models.Index(
                        fields=["organization", "refund_date"],
                        name="orders_refu_organiz_4c9802_idx",
                    ),
                    models.Index(
                        fields=["order"], name="orders_refu_order_i_341cd7_idx"
                    ),
                ],
                "unique_together": {("organization", "external_id")},
            },
        ),
    ]
