# Generated by Codex on 2026-02-05

from django.db import migrations, models
import django.db.models.deletion
from pgvector.django import VectorExtension, VectorField, HnswIndex


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_remove_apikey_accounts_ap_organiz_18cc7e_idx_and_more"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("default_start_date", models.DateField(blank=True, null=True)),
                ("default_end_date", models.DateField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_threads",
                        to="accounts.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Thread",
                "verbose_name_plural": "Chat Threads",
                "indexes": [models.Index(fields=["organization", "created_at"], name="ai_chatthre_organiz_f26812_idx")],
            },
        ),
        migrations.CreateModel(
            name="RagDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("metrics_summary", "Metrics Summary"),
                            ("orders_summary", "Orders Summary"),
                            ("campaigns_summary", "Campaigns Summary"),
                        ],
                        max_length=40,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("content", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("embedding", VectorField(blank=True, dimensions=1536, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_documents",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG Document",
                "verbose_name_plural": "RAG Documents",
                "indexes": [
                    models.Index(
                        fields=["organization", "doc_type", "start_date", "end_date"],
                        name="ai_ragdoc_organiz_9c6f1c_idx",
                    ),
                    HnswIndex(
                        name="rag_doc_embedding_hnsw",
                        fields=["embedding"],
                        m=16,
                        ef_construction=200,
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("citations", models.JSONField(blank=True, default=list)),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.chatthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "indexes": [models.Index(fields=["thread", "created_at"], name="ai_chatmess_thread__b74dfa_idx")],
            },
        ),
    ]
