# Generated by Django 5.1.8 on 2026-01-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Meta", "Meta"),
                            ("Google", "Google"),
                            ("TikTok", "TikTok"),
                            ("Snapchat", "Snapchat"),
                            ("X", "X"),
                            ("Klaviyo", "Klaviyo"),
                            ("salla", "Salla"),
                            ("shopify", "Shopify"),
                        ],
                        max_length=50,
                    ),
                ),
                ("campaign", models.CharField(blank=True, max_length=500)),
                ("creative_url", models.URLField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Pending", "Pending")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("purchase", "Purchase"),
                            ("refund", "Refund"),
                            ("add_to_cart", "Add to Cart"),
                            ("checkout", "Checkout"),
                            ("page_view", "Page View"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "order_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribution_events",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribution Event",
                "verbose_name_plural": "Attribution Events",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="attribution_organiz_696113_idx"
                    ),
                    models.Index(
                        fields=["source"], name="attribution_source_c7e334_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="attribution_timesta_a57e43_idx"
                    ),
                    models.Index(
                        fields=["status"], name="attribution_status_b07c54_idx"
                    ),
                    models.Index(
                        fields=["order_id"], name="attribution_order_i_cfc560_idx"
                    ),
                    models.Index(
                        fields=["event_id"], name="attribution_event_i_d2f027_idx"
                    ),
                    models.Index(
                        fields=["organization", "timestamp"],
                        name="attribution_organiz_153994_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClickTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("store_id", models.CharField(db_index=True, max_length=255)),
                ("platform", models.CharField(max_length=50)),
                ("click_id", models.CharField(db_index=True, max_length=255)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("landing_page", models.URLField(max_length=2000)),
                ("referrer", models.URLField(blank=True, max_length=2000)),
                ("utm_source", models.CharField(blank=True, max_length=255)),
                ("utm_medium", models.CharField(blank=True, max_length=255)),
                ("utm_campaign", models.CharField(blank=True, max_length=255)),
                ("utm_content", models.CharField(blank=True, max_length=255)),
                ("utm_term", models.CharField(blank=True, max_length=255)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("converted", models.BooleanField(default=False)),
                ("conversion_order_id", models.CharField(blank=True, max_length=255)),
                ("conversion_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "conversion_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_tracking",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Click Tracking",
                "verbose_name_plural": "Click Tracking",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="attribution_organiz_4063e9_idx"
                    ),
                    models.Index(
                        fields=["store_id"], name="attribution_store_i_1812fc_idx"
                    ),
                    models.Index(
                        fields=["platform"], name="attribution_platfor_bd1239_idx"
                    ),
                    models.Index(
                        fields=["click_id"], name="attribution_click_i_175f67_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="attribution_timesta_7cadf8_idx"
                    ),
                    models.Index(
                        fields=["converted"], name="attribution_convert_5e4729_idx"
                    ),
                    models.Index(
                        fields=["organization", "timestamp"],
                        name="attribution_organiz_e444c9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PixelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("store_id", models.CharField(db_index=True, max_length=255)),
                ("event_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("session_started_at", models.DateTimeField(blank=True, null=True)),
                ("session_page_views", models.IntegerField(default=0)),
                ("platform", models.CharField(blank=True, max_length=50)),
                (
                    "click_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("click_timestamp", models.DateTimeField(blank=True, null=True)),
                ("landing_page", models.URLField(blank=True, max_length=2000)),
                ("utm_source", models.CharField(blank=True, max_length=255)),
                ("utm_medium", models.CharField(blank=True, max_length=255)),
                ("utm_campaign", models.CharField(blank=True, max_length=255)),
                ("attribution_method", models.CharField(blank=True, max_length=50)),
                ("page_url", models.URLField(blank=True, max_length=2000)),
                ("page_path", models.CharField(blank=True, max_length=500)),
                ("page_referrer", models.URLField(blank=True, max_length=2000)),
                ("page_title", models.CharField(blank=True, max_length=500)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                (
                    "order_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "order_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("is_new_customer", models.BooleanField(blank=True, null=True)),
                ("pixel_version", models.CharField(blank=True, max_length=20)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "attribution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("unmatched", "Unmatched"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("matched_order_id", models.CharField(blank=True, max_length=255)),
                (
                    "match_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixel_events",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pixel Event",
                "verbose_name_plural": "Pixel Events",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="attribution_organiz_d96094_idx"
                    ),
                    models.Index(
                        fields=["store_id"], name="attribution_store_i_f2264f_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="attribution_event_t_7763b1_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="attribution_timesta_b8a28f_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="attribution_session_ae4722_idx"
                    ),
                    models.Index(
                        fields=["click_id"], name="attribution_click_i_e29629_idx"
                    ),
                    models.Index(
                        fields=["order_id"], name="attribution_order_i_fce819_idx"
                    ),
                    models.Index(
                        fields=["attribution_status"],
                        name="attribution_attribu_bc44ed_idx",
                    ),
                    models.Index(
                        fields=["organization", "timestamp"],
                        name="attribution_organiz_810a9b_idx",
                    ),
                ],
            },
        ),
    ]
