# Generated by Django 5.1.8 on 2026-02-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apikey",
            name="accounts_ap_organiz_18cc7e_idx",
        ),
        migrations.RemoveIndex(
            model_name="apikey",
            name="accounts_ap_key_has_530f60_idx",
        ),
        migrations.RemoveIndex(
            model_name="membership",
            name="accounts_me_user_id_c9730d_idx",
        ),
        migrations.RemoveIndex(
            model_name="membership",
            name="accounts_me_organiz_1de7a0_idx",
        ),
        migrations.RemoveIndex(
            model_name="membership",
            name="accounts_me_user_id_ca92ca_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="accounts_or_slug_7a4a7c_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="accounts_or_clerk_o_f8e924_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_clerk_i_3e5530_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_email_74c8d6_idx",
        ),
    ]
