# Generated by Django 5.1.8 on 2026-01-31 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("salla", "Salla"),
                            ("shopify", "Shopify"),
                            ("meta", "Meta"),
                            ("google", "Google"),
                            ("tiktok", "TikTok"),
                            ("snapchat", "Snapchat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("_access_token", models.TextField(db_column="access_token")),
                (
                    "_refresh_token",
                    models.TextField(blank=True, db_column="refresh_token"),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("account_id", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("is_connected", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
            },
        ),
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(max_length=20)),
                ("state", models.CharField(db_index=True, max_length=255, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_states",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth State",
                "verbose_name_plural": "OAuth States",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("campaigns", "Campaigns"),
                            ("events", "Events"),
                            ("orders", "Orders"),
                            ("metrics", "Metrics"),
                            ("full", "Full"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("records_processed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.integration",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
            },
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["organization"], name="integration_organiz_1151fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["platform"], name="integration_platfor_b112d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["is_connected"], name="integration_is_conn_e06c0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["organization", "platform"],
                name="integration_organiz_a73da7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["account_id"], name="integration_account_4ca850_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("organization", "platform")},
        ),
        migrations.AddIndex(
            model_name="oauthstate",
            index=models.Index(fields=["state"], name="integration_state_8d7d88_idx"),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["organization"], name="integration_organiz_a4e688_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["integration"], name="integration_integra_6877b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["status"], name="integration_status_bf366b_idx"),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["started_at"], name="integration_started_633e63_idx"
            ),
        ),
    ]
